### ISSUE TITLE
BUG : Application Opened & Application Backgrounded on Android device is not tracked

### ISSUE THREAD

**Issue by bacdang2761998** [rudderlabs/rudder-sdk-flutter#103]
**Describe the bug**
- Application Opened & Application Backgrounded ion Android device is not tracked.
- When debugging on android device, I check that when the application is running in the background or open, the runnableTasks is run again before the initialization is complete, it makes the calculation results not as expected.

**Which platform is the issue occurring on**
Is the error occurring on:

- [x] Android

**Comment by desusai7** [comment]
Hey @bacdang2761998, 

Can you please share the SDK initialization snippet you are using ?

**Comment by bacdang2761998** [comment]
Hi @desusai7 
Here is the code in the plugin, it doesn't work. The end result of noOfActivities is -2
`  @Override
  public void onActivityStopped(@NonNull Activity activity) {
    Runnable runnableTask =
        () -> {
          if (RudderSdkFlutterPlugin.trackLifeCycleEvents) {
            noOfActivities -= 1;
            if (noOfActivities == 0) {
              RudderSdkFlutterPlugin.rudderClient.track("Application Backgrounded");
            }
          }
        };
    if (RudderSdkFlutterPlugin.rudderClient == null && !RudderSdkFlutterPlugin.initialized) {
      runnableTasks.add(runnableTask);
      return;
    }
    runnableTask.run();
  }`

**Comment by desusai7** [comment]
Hey @bacdang2761998, 
We've tried reproducing this issue from our end but we couldn't. 
Can you please let us know how exactly you are running the app and on which device you are seeing this issue ?

**Comment by bacdang2761998** [comment]
Hi @desusai7,
I try with FlutterActivity and there is no error, but when extending FlutterFragmentActivity in MainActivity.kt, the above error occurs
`class MainActivity: FlutterFragmentActivity() {}`

**Comment by desusai7** [comment]
Got it, I figured that the issue is happening because `onActivityCreated()` is not getting triggered on the first open of the app, but if you move the app back and forth then again it's getting triggered.

Seems like FlutterFragmentActivity is getting attached to the Flutter Engine even before the RudderPlugin got attached to the engine, hence we are missing the onActivityCreated on the app launch, we will try to come up with a fix for this, we are thinking about using ActivityAware to overcome this.

Will let you know once we fix this, thank you bringing this up to our notice.

**Comment by bacdang2761998** [comment]
That idea is so good. I am very happy for this. Thank you so much.

**Comment by bacdang2761998** [comment]
Hi @desusai7 ,
I updated another version of the app but didn't detect any Application Updated events. I'm using Flutter v3.7.9/Dart 2.19.6.
What is the reason here?

**Comment by desusai7** [comment]
Hey @bacdang2761998, 

1. Do you have the Automatic Tracking of life cycle events enabled before and after the update of the app?
2. Were you seeing this issue as well on Android?
3. Can you please confirm if you've updated the build number and version number in the latest version?

**Comment by bacdang2761998** [comment]
Hey @desusai7 
1. Is it this? `builder.withMobileConfig(MobileConfig(trackLifecycleEvents: true));`
2. I'm not sure if it happens on iOS but on my Android it happens
3. I definitely used your latest version available on pub.dev

**Comment by desusai7** [comment]
SDK will trigger an `Application Updated` event only when you already have a version of the app installed on your device and then you have updated the app to the latest version by downloading it from any PlayStore/Appstore.

SDK will get to know that application is updated by observing the new version number of the app.

**Comment by bacdang2761998** [comment]
Thank you! Your answer helped my problem.
