### ISSUE TITLE
Support for Flutter Web?

### ISSUE THREAD

**Issue by gdelgado11** [rudderlabs/rudder-sdk-flutter#11]
Do you plan to add support for flutter web ?

**Comment by chandrabezzo** [comment]
Hi @gdelgado11 I think this package can support for Flutter Web when RudderStack native SDK for javascript available. But, we can improve for support Flutter web using REST API from RudderStack.

**Comment by desusai7** [comment]
Yes, We are planning to provide support for Flutter Web through our JS SDK in the next quarter. Mean while we greatly encourage open source contributions too !

**Comment by itsnitigya** [comment]
Any update on this?
