### ISSUE TITLE
Feature Request: Expose withCollectDeviceId

### ISSUE THREAD

**Issue by andreasgangso** [rudderlabs/rudder-sdk-flutter#119]
Hi, can you expose the new "withCollectDeviceId" configuration option which was added for android in rudder-sdk-android v1.18.0?

https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-android-sdk/#withcollectdeviceid

**Comment by desusai7** [comment]
Hey @andreasgangso, 

The work for this was already in progress [here](https://github.com/rudderlabs/rudder-sdk-flutter/pull/117)

**Comment by desusai7** [comment]
Hey @andreasgangso, 

This feature has been released along with version `2.5.0` of the Flutter SDK.
