### ISSUE TITLE
BUG : ARC Semantic Issue after updating XCode to version 15

### ISSUE THREAD

**Issue by manoelsrs** [rudderlabs/rudder-sdk-flutter#124]
**Describe the bug**
Hey Guys, I'm facing this issue after updating XCode to version 15

I Can't build an app on either emulator or physical device.

```
Could not build the precompiled application for the device.
ARC Semantic Issue (Xcode): No visible @interface for 'RSDBEncryption' declares the selector 'initWithKey:enable:'
/.pub-cache/hosted/pub.dev/rudder_plugin_ios-2.4.0/ios/Classes/RudderSdkFlutterPlugin.m:193:64
```

**Which platform is the issue occurring on**
Is the error occurring on:

- [ ] Android
- [x] iOS
- [ ] Both Android and iOS

**Version of the _Flutter_ SDK**
Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.1)
[✓] Connected device (4 available)
[✓] Network resources
```

Rudder SDK Flutter Version:
```
rudder_sdk_flutter: ^2.5.0
rudder_sdk_flutter_platform_interface: ^2.3.0
```

Could you please help me?

Thank you very much.

**Comment by desusai7** [comment]
Hey @manoelsrs, 

We are looking into this

**Comment by fitterfly-parth** [comment]
I have Xcode 14.3.1 and rudder_sdk_flutter: ^2.2.0

Still I’m facing this issue.

**Comment by desusai7** [comment]
Hello @manoelsrs, @fitterfly-parth,

We have released a fix for this, can you please try upgrading to version `2.5.1` of the SDK and let us know how this goes ?

**Comment by manoelsrs** [comment]
@desusai7 it worked! Thank you very much, you solved it very quickly 🚀 .
