### ISSUE TITLE
BUG : Can't use session recording on Web environment

### ISSUE THREAD

**Issue by Kiruel** [rudderlabs/rudder-sdk-flutter#151]
**Describe the bug**
Please provide the following information:

1. I want to use session record from PostHog on a Web environment. 

**Which platform is the issue occurring on**
Is the error occurring on:

- [X] Web

**Expected behavior**
Should send session record to postHog without any setting (at-least on web env).

**To Reproduce**
Steps to reproduce the behaviour:

1. Initialise Flutter SDK on web env
2. Make some events
3. No session record send to posthog.

**Version of the _Flutter_ SDK**
Please provide the following information:

1. The version of the Rudder Flutter SDK you are using (e.g., Rudder Flutter SDK v1.0.0)
     -   rudder_sdk_flutter: ^2.8.0

**SDK initialisation snippet**
Share the code snippet used for initializing the Flutter SDK.

We use our own dataplaneurl and our own destSDKBaseURL.
```dart
  _rudderController = RudderController.instance;
 final RudderConfigBuilder builder = RudderConfigBuilder();
    builder.withDataPlaneUrl('URL');
    builder.withControlPlaneUrl('URL');
    builder.withLogLevel(RudderLogger.NONE);
    builder.withWebConfig(
      WebConfig(
        destSDKBaseURL: 'URL',
      ),
    );
    _rudderController?.initialize(
      dotenv.env['RUDDERSTACK_WRITE_KEY']!,
      config: builder.build(),
    );

```

**Framework version of the SDK**
```bash
➜  pia_narrative git:(main) ✗ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.0 23A344 darwin-arm64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.85.2)
[✓] Network resources

• No issues found!

```

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
It work when send simple event. But not session record.

**Comment by desusai7** [comment]
Hey @Kiruel, 

Were you using posthog through device mode or cloud mode ?

**Comment by Kiruel** [comment]
We use device mode.
<img width="544" alt="Screenshot 2024-02-01 at 14 19 50" src="https://github.com/rudderlabs/rudder-sdk-flutter/assets/8250175/9629ad68-fb44-476d-9305-470dc36397ef">

**Comment by desusai7** [comment]
Can you please share your website url / your write key to help us understand more about the issue ?

You can DM them through slack as well by joining our community

**Comment by Kiruel** [comment]
I just DM you on slack thanks.

**Comment by fit-jose** [comment]
Is this still not available in flutter web? if so, it should be made clear in the documentation

https://www.rudderstack.com/docs/sources/event-streams/sdks/session-tracking/
