### ISSUE TITLE
Feature Request: Upgrade rudder_plugin_web to use js ^0.7.1

### ISSUE THREAD

**Issue by KhaledAbdElNasserAhmed** [rudderlabs/rudder-sdk-flutter#157]
I am not able to use the latest location package version as it depends on a newer Js version.

**Describe the solution you'd like**
Kindly update the rudder_plugin_web to use  js ^0.7.1 or higher

**Additional context**
` [feature\home] flutter pub get --no-example
Resolving dependencies...
Because location >=6.0.0 depends on location_web ^5.0.0 which depends on js ^0.7.1, location >=6.0.0 requires js ^0.7.1.
Because rudder_plugin_web 2.6.0 depends on js ^0.6.3 and no versions of rudder_plugin_web match >2.6.0 <3.0.0, rudder_plugin_web ^2.6.0 requires js ^0.6.3.
Thus, location >=6.0.0 is incompatible with rudder_plugin_web ^2.6.0.
And because rudder_sdk_flutter 2.9.0 depends on rudder_plugin_web ^2.6.0, location >=6.0.0 is incompatible with rudder_sdk_flutter 2.9.0.
Because every version of common from path depends on rudder_sdk_flutter ^2.9.0 and no versions of rudder_sdk_flutter match >2.9.0 <3.0.0, every version of common from path requires rudder_sdk_flutter 2.9.0.
Thus, location >=6.0.0 is incompatible with common from path.
So, because home depends on both common from path and location ^6.0.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on location: flutter pub add location:^5.0.3
exit code 1 `

**Comment by 1abhishekpandey** [comment]
Hey @KhaledAbdElNasserAhmed,
Can you please utilise the latest version of the `rudder_plugin_web` and check if your issue is resolved or not?
