### ISSUE TITLE
Feature request: How to disable metrics collection?

### ISSUE THREAD

**Issue by An1metall** [rudderlabs/rudder-sdk-flutter#178]
i'm using rudder_sdk_flutter: 2.6.0 and constantly see in logs request like
https://selfhosted.rudderstack.server/rsaMetrics that returns 404 error.

How can i disable metrics collection?

**Comment by 1abhishekpandey** [comment]
Hey @An1metall,

On which platform are you encountering this error—Android, iOS, or Web? Additionally, are you self-hosting the sourceConfig?

If you are not self-hosting, please provide your workspace ID.

**Comment by An1metall** [comment]
No, we are self-hosting only data plane.
I see this request on iOS. Can't check on Android yet.
Workspace Id: 2frCXrQInJr6kDtw8O0UBVH9dFK

**Comment by 1abhishekpandey** [comment]
Hey @An1metall,

We have disabled metrics collection for your workspace. Please let us know if you continue to encounter the same error.
