### ISSUE TITLE
BUG : Cannot build android APK with rudder_sdk_flutter on fresh flutter project

### ISSUE THREAD

**Issue by JJCLane** [rudderlabs/rudder-sdk-flutter#184]
**Describe the bug**
Please provide the following information:

The package cannot be used after upgrading Flutter and Gradle versions. I tried it with a fresh flutter project and it also doesn't build after just including `rudder_sdk_flutter` as a dependency. Even if you include a namespace to satisfy Gradle, you get the following error instead:

```
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rudder_plugin_android:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: {redacted}\rudder_plugin_android\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 24s
Running Gradle task 'assembleRelease'...                           25.3s
Gradle task assembleRelease failed with exit code 1
````

**Which platform is the issue occurring on**
Is the error occurring on:

- [X] Android
- [ ] iOS
- [ ] Both Android and iOS

**Expected behavior**
The APK should build successfully with no errors.

**To Reproduce**
Steps to reproduce the behaviour:

1. Install Flutter SDK
2. `flutter build apk`
3. See the error

**Screenshots**
````
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':rudder_plugin_android'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 798ms
Running Gradle task 'assembleRelease'...                         1,434ms
Gradle task assembleRelease failed with exit code 1
````

**Version of the _Flutter_ SDK**
Please provide the following information:

1. The version of the Rudder Flutter SDK you are using: tried 2.9.0 and 3.0.0
2. The versions of the Rudder Android and iOS SDKs utilized within Flutter: rudder_plugin_android v3.0.0

**SDK initialisation snippet**
N/A

**Framework version of the SDK**
Tried with:
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (4 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

**Comment by 1abhishekpandey** [comment]
Hey @JJCLane,

Thank you for raising this issue, I'll look into this.

**Comment by 1abhishekpandey** [comment]
Hey @JJCLane,

Thanks for providing the detailed steps. We have identified the issue and will deliver the fix by the end of this month.

As a temporary solution, you can use this to unblock yourself for now. Please add the following to your root `build.gradle` file:
```
subprojects {
    afterEvaluate {
        android {
            compileSdkVersion 34
        }
    }
}
```

Just before this:
```
rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
```

(We will do our best to prioritize this fix soon.)

**Comment by 1abhishekpandey** [comment]
We have released a fix in our latest version, please update to the `rudder_sdk_flutter: ^3.0.1`.

**Comment by JJCLane** [comment]
Thank you!
