### ISSUE TITLE
BUG : version solving failed!

### ISSUE THREAD

**Issue by moses-team-ge** [rudderlabs/rudder-sdk-flutter#185]
After version update to 3.0.0 `dart pub get` shows an error:

```
Because rudder_integration_firebase_flutter depends on rudder_sdk_flutter ^2.10.0 which depends on rudder_sdk_flutter_platform_interface ^2.9.0, rudder_sdk_flutter_platform_interface ^2.9.0 is required.
So, because rudder_integration_firebase_flutter depends on rudder_sdk_flutter_platform_interface ^3.0.0, version solving failed.
```

Please provide the following information:

1. Set `rudder_integration_firebase_flutter: ^3.0.0` and `rudder_sdk_flutter: ^3.0.0`
2. Run `dart pub get`
3. Issue stacktrace: https://pub.dev/packages/rudder_integration_firebase_flutter/versions/3.0.0/score/log.txt

- [x] Android
- [x] iOS
- [x] Both Android and iOS

**Expected behavior**
Correct installation of pub package

**Comment by saikumarrs** [comment]
Hi @moses-team-ge
Thanks for reaching out to us.
We'll look into it and get back to you.

**Comment by 1abhishekpandey** [comment]
Hey @moses-team-ge,

Thank you for raising this issue.

We have identified the issue and are actively working on providing a fix. In the meantime, we kindly request you to temporarily use the following versions:
1. rudder_sdk_flutter: 2.10.0
2. rudder_integration_firebase_flutter: 2.3.0

These versions should avoid the conflict by ensuring compatibility with rudder_sdk_flutter_platform_interface ^2.9.0.

We will notify you once the fix is provided.

**Comment by 1abhishekpandey** [comment]
So, to clarify, you want to use the latest versions of the following dependencies:

1. Firebase-Android: `com.google.firebase:firebase-analytics`
2. Firebase-iOS: `FirebaseAnalytics`

(Our Flutter-Firebase internally uses the above Firebase SDKs.)

**Comment by moses-team-ge** [comment]
> We will notify you once the fix is provided.

Thank you! Waiting for fix!

**Comment by 1abhishekpandey** [comment]
Thanks for the confirmation.

Regarding the Flutter issue, we will prioritize it soon and aim to release a fix by the end of the month.
For the Firebase update you mentioned, I’ll forward this request to our team for further consideration.

**Comment by sergei-moiseev** [comment]
> Just to clarify, @sergei-moiseev, are you from the same team that raised this issue?​

Absolutely. =)

**Comment by moses-team-ge** [comment]
Okay... but now there is another issue with the FirebaseCore pod update. 
Should I separate this into a new task?

```
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.6.0, which depends on
      Firebase/CoreOnly (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseCore (= 11.2.0)

    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 4.1.3, which depends on
      Firebase/Crashlytics (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseCrashlytics (~> 11.2.0) was resolved to 11.2.0, which depends on
          FirebaseCore (~> 11.0)

    rudder_integration_firebase_flutter (from `.symlinks/plugins/rudder_integration_firebase_flutter/ios`) was resolved to 2.0.0, which depends on
      Rudder-Firebase (= 3.0.0) was resolved to 3.0.0, which depends on
        FirebaseAnalytics (= 10.3.0) was resolved to 10.3.0, which depends on
          FirebaseCore (~> 10.0)
```

**Comment by 1abhishekpandey** [comment]
I can see there’s a conflict with `FirebaseCore`. Our Firebase iOS SDK requires `FirebaseCore (~> 10.0)`, while your native `FirebaseCore` is using a more recent version, `11.2.0`.

If possible, you could override the FirebaseCore version to use an older version of the SDK that is compatible with ours. Alternatively, you can wait a little longer, as we are planning to release an update that will support `FirebaseCore 11.4.0`. (It'll take some time.)

**Comment by moses-team-ge** [comment]
Okay. I'm waiting for fix. Thank you!

**Comment by 1abhishekpandey** [comment]
Hey @moses-team-ge, 

We’ve released an updated version of the Flutter Firebase integration with the latest Firebase Android and iOS SDKs. Please update to version `rudder_integration_firebase_flutter: 4.1.0`.
