### ISSUE TITLE
BUG : Application lifecycle events aren't logged

### ISSUE THREAD

**Issue by Mo0Khaled** [rudderlabs/rudder-sdk-flutter#192]
**Describe the bug**
The Application lifecycle events isn't logged at all none of them, and I din't override the values on the builder, as I understand it should be logged be default.

**Which platform is the issue occurring on**
Is the error occurring on:
- [1] Both Android and iOS

**SDK initialisation snippet**
Flutter 3.24.1

**Framework version of the SDK**
rudder_sdk_flutter: ^3.0.1

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
all correct, other events working pretty good `track`, `screen`.

**Comment by 1abhishekpandey** [comment]
Hey @Mo0Khaled ,

Can you please provide the complete Rudder-Flutter SDK initialisation snippet?

**Comment by Mo0Khaled** [comment]
> Hey @Mo0Khaled ,
> 
> Can you please provide the complete Rudder-Flutter SDK initialisation snippet?

Sure thing HYG:

```dart

     final builder = RudderConfigBuilder();

     final rudderTokenKey = BuildConfig.of().rudderTokenKey;
     final rudderDataPlaneUrl = BuildConfig.of().rudderDataPlaneUrl;

     builder.withDataPlaneUrl(rudderDataPlaneUrl);
     rudderClient.initialize(
       rudderTokenKey,
       config: builder.build(),
       )
```

**Comment by 1abhishekpandey** [comment]
Just to clarify, by this:
> as I understand it should be logged be default.

Where exactly are you referring to? Is it the IDE logcat or the RudderStack dashboard?

**Comment by Mo0Khaled** [comment]
> Just to clarify, by this:
> 
> > as I understand it should be logged be default.
> 
> Where exactly are you referring to? Is it the IDE logcat or the RudderStack dashboard?

I mean the dashboard but as we talked about on the other issue, we use customer.io dashboard

**Comment by 1abhishekpandey** [comment]
Could you please check the RudderStack—Flutter source `live events` tab (https://app.rudderstack.com/) and see if any lifecycle events (e.g., Application Installed, Application Opened, or Application Backgrounded) are reported or not?
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/bbef7a35-0fe9-4a46-9dd2-8513433cc530">

**Comment by Mo0Khaled** [comment]
> Could you please check the RudderStack—Flutter source `live events` tab (https://app.rudderstack.com/) and see if any lifecycle events (e.g., Application Installed, Application Opened, or Application Backgrounded) are reported or not?
> 
> <img width="1422" alt="image" src="https://github.com/user-attachments/assets/bbef7a35-0fe9-4a46-9dd2-8513433cc530">
> 
> 

Tested it now and nothing there too.

Is there an extra code should be written to make this work?

**Comment by 1abhishekpandey** [comment]
Hey @Mo0Khaled,

Could you please let us know if your issue has been resolved or if you need any further assistance?

**Comment by Mo0Khaled** [comment]
Hello @1abhishekpandey ,

still not working we have tried it on version 2.9.0 and it's working is this information helpful for you so you can help me find the issue?

**Comment by 1abhishekpandey** [comment]
Could you please provide this and attempt to install the Flutter SDK in a new sample app?

> If it still doesn't work, please install the app fresh, run it for 30 seconds, move the app to the background and foreground, and share the complete Android logcat filtered by RudderSDK. We can then verify whether lifecycle events are made or not.

By the way, there have been no changes to the lifecycle from v2.9.0 to the latest version.

**Comment by 1abhishekpandey** [comment]
Hey @Mo0Khaled,

Is there any update on this?

**Comment by Mo0Khaled** [comment]
it's working on a new project will close it for now, thanks for your support @1abhishekpandey 💯 🥇
