### ISSUE TITLE
BUG : Viewed and screen appended to the `screen` event by default

### ISSUE THREAD

**Issue by Mo0Khaled** [rudderlabs/rudder-sdk-flutter#193]
**Describe the bug**
Viewed and screen appended to the `screen` event name by default and I need to remove them as we have a structure for the events and we also depend on these values and we have a huge old data on customer.io, so we need to keep the current structure.

Example:
screenName I passed to the SDK: `Account Screen Opened`
event shown in the dashboard: `Viewed Account Screen Opened Screen`.

How can we remove this?

Also if you need any help to remove these texts or make it optional I can contribute on both IOS and Android.
Thanks in advance.

**Which platform is the issue occurring on**
Is the error occurring on:
- [1] Both Android and iOS

**SDK initialisation snippet**
Flutter 3.24.1

**Framework version of the SDK**
rudder_sdk_flutter: ^3.0.1

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
All correct.

**Comment by Mo0Khaled** [comment]
@1abhishekpandey  Updated the issue description with an example to make it more clear.

**Comment by 1abhishekpandey** [comment]
Hey @Mo0Khaled,

I guess you're trying to send screen events from the Flutter source to Customer.IO in cloud mode (as we don't have Customer.IO, as a device mode in Flutter yet) and in that process, those values are appended. I can see the screen event append those values over [here](https://github.com/rudderlabs/rudder-transformer/blob/640a11eb3dca5735fed3ad9ad5bd058974b069d6/src/v0/destinations/customerio/transform.js#L100). I would request you raise another issue on that repo, as that is maintained by a different team.

Note: SDK keeps the screen event name based on whatever value you provide. But integration can modify the event name based on their use case logic.

**Comment by Mo0Khaled** [comment]
Hey @1abhishekpandey Thank you.

I will raise another issue there.
