### ISSUE TITLE
mistakes in your documentation

### ISSUE THREAD

**Issue by Yoda-Man** [rudderlabs/rudder-sdk-flutter#48]
your code is wrong in Readme.md

Initialize RudderClient

this is a bit better

  RudderConfigBuilder builder = RudderConfigBuilder();
  builder.withDataPlaneUrl("https://rudderstacgwyx.dataplane.rudderstack.com");
  builder.withControlPlaneUrl("https://api.rudderlabs.com");
  builder.withLogLevel(RudderLogger.VERBOSE);
  RudderOption options = RudderOption();
  options.putIntegration("Amplitude", true);
  const String writeKey = "write_key";
  rudderClient.initialize(writeKey, config: builder.build(), options: options);

![image](https://user-images.githubusercontent.com/11532865/182553290-8398021d-e4ca-48d4-a63d-19284ab20af8.png)

**Comment by desusai7** [comment]
Hey @Yoda-Man, 

Thank you for raising the issue and giving us a detailed explanation.

DataPlaneUrl and WriteKey vary from user to user. Hence we documented it with some dummy values. And users are expected to replace those dummy values with their write keys and data plane URLs.

We wanted the code snippets in the Readme to be minimal and simple so they would just contain details required to start immediately.

Detailed documentation about the SDK regarding RudderConfigBuilder,  Configuring Integrations Object through RudderOption, etc... are always available [here](https://www.rudderstack.com/docs/sources/sdks/rudderstack-flutter-sdk/). 

However, we are revamping the Code-Snippets of all SDKs, we will make things more explicit in those changes. 

Closing this issue for now. Please let us know if there is anything else.

**Comment by Yoda-Man** [comment]
I think the Initialize code on the readme is for version 1 of your SDK if people follow it they will get frustrated

**Comment by desusai7** [comment]
Yes, the master branch points to version 1 of the SDK. We also have a branch [2.x](https://github.com/rudderlabs/rudder-sdk-flutter/tree/2.x) which is the source code of version 2.

We are in the process of adding readme for version 2 as well. Meanwhile please refer to version 2 docs [here](https://www.rudderstack.com/docs/sources/sdks/rudderstack-flutter-sdk/flutter-v2/)
