### ISSUE TITLE
Unable to build if I target compileSdkVersion 33

### ISSUE THREAD

**Issue by Yoda-Man** [rudderlabs/rudder-sdk-flutter#50]
Unable to build if I target compileSdkVersion 33 in build.gradle

**Comment by desusai7** [comment]
Hey @Yoda-Man, 

Can you please share more details about the issue, for example, the error you are seeing, logs, or anything which would help us to understand the issue more?

**Comment by Yoda-Man** [comment]
My apologies when I got back into the project to try rebuild and send you the logs it worked.

**Comment by desusai7** [comment]
Okay, no worries. Closing the issue for now. 
If you face the issue again, please re-open this and share all the available details about the issue.
