### ISSUE TITLE
Will update to null safety?

### ISSUE THREAD

**Issue by aline-yuca** [rudderlabs/rudder-sdk-flutter#6]
Hello, 

This plugin will update to null safety?

**Comment by deborahcarvalho** [comment]
I would like to know that as well...can anyone answer? @desusai7 @arnab-p

**Comment by abed-binary** [comment]
I have a [PR](https://github.com/rudderlabs/rudder-sdk-flutter/pull/7), hopefully they will have a look at it.

**Comment by desusai7** [comment]
Hello Guys,
We are also discussing that. Will have an update soon.
@abed-binary Thank you for the PR. We will definitely have a look at it

**Comment by aline-yuca** [comment]
Hey guys,

Any news?

**Comment by chandrabezzo** [comment]
Hi @aline-yuca I have been made pull request #14 for null safety, merge app center to this package, and follow effective dart to follow standard code from Google. My pull request still in review by team.

**Comment by desusai7** [comment]
Hello Guys,
We just release `rudder_sdk_flutter: ^1.0.2` with Null Safety [here](https://pub.dev/packages/rudder_sdk_flutter/versions/1.0.2).
Thank you all for the support
