### ISSUE TITLE
Cannot receive any events in a flutter release build (only on Android)

### ISSUE THREAD

**Issue by ghassenchaar96** [rudderlabs/rudder-sdk-flutter#77]
Hello!

I have a flutter  and have successfully integrated `rudder_sdk_flutter` along with `rudder_integration_braze_flutter` SDKs.
When I run my app in debug/dev mode, everything is working fine. I got my events in flutter source in Rudderstack, and those events are then sent to Braze (iOS and android).

I’m actually having an issue while running my app in release mode on android `flutter run --release`.
I don’t see events coming to my flutter source on Rudderstack, so nothing is happening on Braze as well.

This only happens when running the app in **release mode** and only on **android**.

Am I missing something here?

Here's how I initialize the rudder client:

```
void initRudderstack() {
  RudderConfigBuilder builder = RudderConfigBuilder();

  builder.withDataPlaneUrl(dotenv.env["RUDDESRSTACK_DATA_PLANE"]!);
  builder.withControlPlaneUrl("https://api.rudderlabs.com");
  builder.withLogLevel(RudderLogger.VERBOSE);

// This is used to integrace rudderstack-braze connection via device mode
  builder.withFactory(RudderIntegrationBrazeFlutter());

  RudderOption options = RudderOption();

  String writeKey = dotenv.env["RUDDESRSTACK_WRITE_KEY"]!;

  RudderClient.instance
      .initialize(writeKey, config: builder.build(), options: options);

}

```

I'm using:
```
  rudder_integration_braze_flutter: 1.0.2
  rudder_sdk_flutter: ^2.3.0
```

flutter doctor -v 

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.5.1 21G83 darwin-arm64, locale en-FR)
    • Flutter version 3.7.3 on channel stable at /Users/ghassen/dev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (7 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ghassen/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ghassen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • EDA52 (mobile)  • 22021B1B40 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos      • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm64
    • Chrome (web)    • chrome     • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by desusai7** [comment]
Hey @ghassenchaar96, 

Can you please share the logs with us when you are seeing this issue ?

and also were you using any proguard rules ?

**Comment by desusai7** [comment]
@ghassenchaar96, were you able to resolve the issue ?

**Comment by desusai7** [comment]
Disabling `shrinkResources` and `minifyEnabled` can result in a larger APK size because unused code and resources may still be present in the APK.

And you see no events flowing to Rudderstack when you enabled both of the above settings because some of the SDK files are removed during the minification process.

In order to ignore the SDK files from being removed during the minification process you need to add some proguard rules to your app as documented [here](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v2/#do-i-need-to-add-anything-to-my-android-proguard-rules).

**Comment by ghassenchaar96** [comment]
Thank you for the clarification @desusai7, I will test it then.

**Comment by 1abhishekpandey** [comment]
Hey @ghassenchaar96 have you tested it? Please let us know if it resolves your issues.

**Comment by desusai7** [comment]
Hey @ghassenchaar96, we are closing this issue for now, please open it in future if the issue persists
