### ISSUE TITLE
Feature Request: Conditionally SDK Integration for Web

### ISSUE THREAD

**Issue by chandrabezzo** [rudderlabs/rudder-sdk-flutter#92]
**Is your feature request related to a problem? Please describe.**
Clear ways to [install sdk for web](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/quick-start-guide/#step-1-install-javascript-sdk). When we use several write key for environments case like staging, preview, and production. If we declare directly to index.html file we can't change value conditionally every build.

**Describe the solution you'd like**
How about to build js file from rudderstack SDK then call the file under index.html.

**Describe alternatives you've considered**
Another approach to send from dart side or command line to js side like flutter base href.
```
<!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.
    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.
    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="$FLUTTER_BASE_HREF">
```

**Comment by bardisg** [comment]
Hello @chandrabezzo ,

For such cases like using different secrets per environment/build I would suggest flutter_dotenv and dedicated .env files per environment.

Is this an approach that could be of conveniance to you?

**Comment by 1abhishekpandey** [comment]
Hey @chandrabezzo, can you kidnly confirm if you are satisfied with our suggestion in the previous [message](https://github.com/rudderlabs/rudder-sdk-flutter/issues/92#issuecomment-1534130540)?

**Comment by desusai7** [comment]
Hey @chandrabezzo, 

I just realized that there is an issue with our documentation which directs you to get the JS SDK installation snippet from the JS SDK docs. There it includes the SDK initialization as well and it needs you to declare the write key and the data plane URL in index.html itself. 

But we already had a way to pass the write key, and data plane URL from the dart side, you can just remove the load call in the JS SDK installation code snippet you are using in your index.html similar to our example [here](https://github.com/rudderlabs/rudder-sdk-flutter/blob/25499e381421e618bb2f4c40203dcd3f9cc194c7/packages/example/web/index.html#L34-L46)

**Comment by desusai7** [comment]
@chandrabezzo, can you confirm updating the code snippet in the index.html helped solving your issue?

**Comment by chandrabezzo** [comment]
Hi @desusai7 thanks for the confirm. So, for the latest version we doesn't need to add write key and data plane url via index.html
