### ISSUE TITLE
BUG : Incompatibility with flutter_localizations on  Flutter 3.10.0 

### ISSUE THREAD

**Issue by eliezerben** [rudderlabs/rudder-sdk-flutter#93]
Hello,

After upgrading to flutter 3.10.0, there is incompatibility between the `rudder_sdk_flutter_platform_interface` and `flutter_localizations` because they depend on different versions of `intl` package.

**This is the error I'm seeing when I build the project:**
```
Because every version of flutter_localizations from sdk depends on intl 0.18.0 and every version of rudder_sdk_flutter_platform_interface depends on intl ^0.17.0, flutter_localizations from sdk is incompatible with
  rudder_sdk_flutter_platform_interface.
```

I have the latest version(2.3.1) of rudder_sdk_flutter installed.

**Flutter doctor:**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

**Comment by desusai7** [comment]
Hey @eliezerben,

Thank you for bringing this to our notice, we will fix this and let you know

**Comment by desusai7** [comment]
Hey @spiderion, @eliezerben 

We are working on this, but it might take a while as we are busy with other high-priority items. Can you please unblock yourself using [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) for the time being in the mean time we make a new release ?

**Comment by desusai7** [comment]
Hey @spiderion, @eliezerben, 

We've fixed this issue in version 2.3.2 [here](https://pub.dev/packages/rudder_sdk_flutter/versions/2.3.2), can you please upgrade to it and confirm everything is fine ?

**Comment by pkozlowski93** [comment]
hello @desusai7, encountering the same problem with 2.3.2 as well:
`Because rudder_sdk_flutter >=1.0.2 depends on intl ^0.17.0 and ... depends on intl 0.18.0, rudder_sdk_flutter >=1.0.2 is forbidden.
So, because ... depends on rudder_sdk_flutter 2.3.2, version solving failed.`

**Comment by LaxmikanthMadhyastha** [comment]
any update on this? facing the same issue

**Comment by desusai7** [comment]
Hey @LaxmikanthMadhyastha, @pkozlowski93, 

We are working on this and will release a fix soon

**Comment by eliezerben** [comment]
@desusai7 Works fine now. Thanks.
